### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JamesEdwardMacDonald** [Gameye98/FBBrute#3]
Error :

“No such file or directory”" and how to create a password list and termux-setup-storage

**Comment by TheDarkW3b** [comment]
run
```bash
pkg install nano
```
Inside your fb brute directory run command
```bash
touch PASSWORD_FILE_NAME.txt
```
replace PASSWORD_FILE_NAME with your needed one 

Then run 
```bash
nano PASSWORD_FILE_NAME.txt
```
And add your passwords
